export const mockAssets = [
  {
    id: '1',
    assetTag: 'TYS-LAP-00001',
    type: 'Laptop',
    modelName: 'Dell Latitude 5440',
    serialNum: 'SN12345',
    status: 'Assigned',
    currentHolder: 'John Smith',
    currentHolderId: '3',
    purchaseCost: 1200,
    warrantyEnd: '2026-12-31',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    assetTag: 'TYS-LAP-00002',
    type: 'Laptop',
    modelName: 'MacBook Pro 14',
    serialNum: 'SN12346',
    status: 'Available',
    currentHolder: null,
    currentHolderId: null,
    purchaseCost: 2000,
    warrantyEnd: '2027-06-30',
    createdAt: '2024-01-15',
  },
  {
    id: '3',
    assetTag: 'TYS-MON-00001',
    type: 'Monitor',
    modelName: 'Dell U2724D',
    serialNum: 'SN98765',
    status: 'Assigned',
    currentHolder: 'Jane Doe',
    currentHolderId: '4',
    purchaseCost: 500,
    warrantyEnd: '2026-08-15',
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    assetTag: 'TYS-KEY-00001',
    type: 'Keyboard',
    modelName: 'Logitech MX Keys',
    serialNum: 'SN11111',
    status: 'Available',
    currentHolder: null,
    currentHolderId: null,
    purchaseCost: 150,
    warrantyEnd: '2025-12-31',
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    assetTag: 'TYS-KEY-00002',
    type: 'Keyboard',
    modelName: 'Logitech MX Keys',
    serialNum: 'SN11112',
    status: 'Available',
    currentHolder: null,
    currentHolderId: null,
    purchaseCost: 150,
    warrantyEnd: '2025-12-31',
    createdAt: '2024-02-10',
  },
]

export const mockAssetTypes = [
  { id: '1', name: 'Laptop', code: 'LAP' },
  { id: '2', name: 'Monitor', code: 'MON' },
  { id: '3', name: 'Keyboard', code: 'KEY' },
]

export const mockAssetModels = [
  { id: '1', typeId: '1', name: 'Dell Latitude 5440', manufacturer: 'Dell' },
  { id: '2', typeId: '1', name: 'MacBook Pro 14', manufacturer: 'Apple' },
  { id: '3', typeId: '2', name: 'Dell U2724D', manufacturer: 'Dell' },
  { id: '4', typeId: '3', name: 'Logitech MX Keys', manufacturer: 'Logitech' },
]

export const mockMovements = [
  {
    id: '1',
    assetId: '1',
    action: 'StockIn',
    toStatus: 'Available',
    fromStatus: null,
    performedBy: '2',
    performedByName: 'Purchase Admin',
    performedAt: '2024-01-15',
    notes: 'Initial stock-in from invoice INV-2024-001',
  },
  {
    id: '2',
    assetId: '1',
    action: 'Allocate',
    toStatus: 'Assigned',
    fromStatus: 'Available',
    toUser: '3',
    toUserName: 'John Smith',
    performedBy: '1',
    performedByName: 'Admin User',
    performedAt: '2024-01-20',
    notes: 'Allocated to John Smith',
  },
  {
    id: '3',
    assetId: '3',
    action: 'StockIn',
    toStatus: 'Available',
    fromStatus: null,
    performedBy: '2',
    performedByName: 'Purchase Admin',
    performedAt: '2024-02-01',
    notes: 'Monitor stock-in from invoice INV-2024-002',
  },
  {
    id: '4',
    assetId: '3',
    action: 'Allocate',
    toStatus: 'Assigned',
    fromStatus: 'Available',
    toUser: '4',
    toUserName: 'Jane Doe',
    performedBy: '1',
    performedByName: 'Admin User',
    performedAt: '2024-02-05',
    notes: 'Allocated to Jane Doe',
  },
]

export const mockInvoices = [
  {
    id: '1',
    invoiceNum: 'INV-2024-001',
    vendor: 'Dell Technologies',
    totalAmount: 5600,
    createdAt: '2024-01-15',
    items: [
      { assetNameId: '1', quantity: 2, unitPrice: 1200 },
      { assetNameId: '3', quantity: 3, unitPrice: 500 },
    ],
  },
  {
    id: '2',
    invoiceNum: 'INV-2024-002',
    vendor: 'Logitech',
    totalAmount: 300,
    createdAt: '2024-02-10',
    items: [{ assetNameId: '4', quantity: 2, unitPrice: 150 }],
  },
]
